### ISSUE TITLE
[Feature Request] Add options to make h1 - h6 and p tags

### ISSUE THREAD

**Issue by retan** [jediwade/brackets-htmlformat#3]
I would love to have an option to make `<h1>` - `<h6>` tags and a `<p>` tag. 
In case of heading tags, I would suggest to assign to them `Ctrl + Num` or `Ctrl + Shift + Num` shortcuts (where Num = 1...6). As for the paragraph... well, probably `Ctrl + P`. Though you could leave those blank, to let the user decide.

**Comment by jediwade** [comment]
Updated live with requested feature addition.

**Comment by retan** [comment]
I'm very grateful but there's a problem. I've got the new options in preferences but I cannot assign a number in the key field - the input just doesn't allow me to type anything other than a letter (and `[]\` apparently).

**Comment by jediwade** [comment]
So the way that screen was setup was to limit it to just letters and numbers. Apparently the keycode for the numbers on the numpad are different from those on the number row. Got the numbers fixed, but I am now looking at making it automatically select/check Shift, Alt, and Ctrl based on the keys you are currently pressing. If you need an update now, I can go ahead and push one out in a bit.

**Comment by retan** [comment]
There's no hurry. But now it apears something more fundamental is wrong. After the update, after restarting Brackets the extention doesn't work at all. Sometimes I just see the "HTML format" flick in the menu bar, but it dissapears a split second later. I've tried removing related prefferences from brackets.json - no luck. I've tried disabling/cleaning brackets.json/restarting/enabling - no luck. I've tried deinstall/cleaning brackets.json/restarting/install - no luck. Here is what the relevant part of brackets.json looked like:
```json
    "wadedwalker.brackets.extension.htmlFormat.preferences.boldTag": [
        "Ctrl",
        null,
        null,
        null,
        "B"
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.boldStyle": [
        "Ctrl",
        "Shift",
        null,
        null,
        "B"
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.italicTag": [
        "Ctrl",
        null,
        null,
        null,
        "I"
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.italicStyle": [
        "Ctrl",
        "Shift",
        null,
        null,
        "I"
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.underlineTag": [
        "Ctrl",
        null,
        null,
        null,
        "U"
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.underlineStyle": [
        "Ctrl",
        "Shift",
        null,
        null,
        "U"
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.emptyTag": [
        "Ctrl",
        null,
        null,
        null,
        "T"
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.preferences": [
        "Ctrl",
        "Shift",
        null,
        null,
        ","
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.anchorTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.spanTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.divTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.headerTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.navTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.articleTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.sectionTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.asideTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.footerTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.strikeTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.strikeStyle": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.teletypeTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.teletypeStyle": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.codeTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.variableTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.sampleTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.keyboardTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.citationTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.deletedTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.definitionTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.insertedTag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.boldUsesStrong": true,
    "wadedwalker.brackets.extension.htmlFormat.preferences.italicUsesEm": true,
    "wadedwalker.brackets.extension.htmlFormat.preferences.rightClick": false,
    "debug.showErrorsInStatusBar": false,
    "wadedwalker.brackets.extension.htmlFormat.preferences.paragraphTag": [
        "Ctrl",
        null,
        null,
        null,
        "P"
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.h1Tag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.h2Tag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.h3Tag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.h4Tag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.h5Tag": [
        null,
        null,
        null,
        null,
        ""
    ],
    "wadedwalker.brackets.extension.htmlFormat.preferences.h6Tag": [
        null,
        null,
        null,
        null,
        ""
    ]
```

Here are some messages from dev console, that may be relevant (I've replaced my user name in file path with `***` )
```text
INITIALIZING HTML FORMAT EXTENSION
/utils/DeprecationWarning.js:90 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at Object.<anonymous> (file:///C:/Users/***/AppData/Roaming/Brackets/extensions/user/brackets-htmlformat/main.js:321:24)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
```
This one (shortcuts for indentation) are internal but mayby there's some conflict?
```text
/command/KeyBindingManager.js:580 Fail to nomalize Cmd-Shift-]
/command/KeyBindingManager.js:580 Fail to nomalize Cmd-Shift-[
```

**Comment by jediwade** [comment]
I'm having to do a lot of messing around it. KeyboardEvent keyCodes is something I havent done a lot of messing with, so I'm learning some new stuff with this request. Apparently the keyup/down event has different keyCode values than the keypress event. Looking at changing it to be a keyup event because there is a giant list of keyCodes for that. Going to issue an update in a bit that should fix the numbers (I only have a laptop so I can't check/test the numpad).

**Comment by jediwade** [comment]
I think the Brackets Extension Registry is broken again. Whenever I try to upload a new zip, it says, "The extension package is invalid: The uploaded content is not a valid zip file.". Last time this happened was in April I believe and it lasted over a week if memory serves me correctly. For testing, I suggest using the GitHub download ZIP option, unzip it and overwrite the contents of the current brackets-htmlformat folder in your Brackets "users" extension folder.

**Comment by retan** [comment]
I've used the zip from github... And it works! :laughing:  - both: the preferences and the actual shortcuts and for both: the numpad and numrow.
I've done a test in dev tools (in Brackets). The keypress event gives the same values in both case (numpad and numrow).

```text
$(window).on('keypress',function(e) {console.debug('keypress keyCode:'+e.keyCode+' which:'+e.which)})
[Window]
$(window).on('keyup',function(e) {console.debug('keyup keyCode:'+e.keyCode+' which:'+e.which)})
[Window]
/* HERE I START TYPING '0123456789' ON NUMPAD */
undefined
VM2702:2 keypress keyCode:48 which:48
VM2705:2 keyup keyCode:96 which:96
VM2702:2 keypress keyCode:49 which:49
VM2705:2 keyup keyCode:97 which:97
VM2702:2 keypress keyCode:50 which:50
VM2705:2 keyup keyCode:98 which:98
VM2702:2 keypress keyCode:51 which:51
VM2705:2 keyup keyCode:99 which:99
VM2702:2 keypress keyCode:52 which:52
VM2705:2 keyup keyCode:100 which:100
VM2702:2 keypress keyCode:53 which:53
VM2705:2 keyup keyCode:101 which:101
VM2702:2 keypress keyCode:54 which:54
VM2705:2 keyup keyCode:102 which:102
VM2702:2 keypress keyCode:55 which:55
VM2705:2 keyup keyCode:103 which:103
VM2702:2 keypress keyCode:56 which:56
VM2705:2 keyup keyCode:104 which:104
VM2702:2 keypress keyCode:57 which:57
VM2705:2 keyup keyCode:105 which:105
/* HERE I START TYPING '0123456789' ON NUMROW */
undefined
VM2702:2 keypress keyCode:48 which:48
VM2705:2 keyup keyCode:48 which:48
VM2702:2 keypress keyCode:49 which:49
VM2705:2 keyup keyCode:49 which:49
VM2702:2 keypress keyCode:50 which:50
VM2705:2 keyup keyCode:50 which:50
VM2702:2 keypress keyCode:51 which:51
VM2705:2 keyup keyCode:51 which:51
VM2702:2 keypress keyCode:52 which:52
VM2705:2 keyup keyCode:52 which:52
VM2702:2 keypress keyCode:53 which:53
VM2705:2 keyup keyCode:53 which:53
VM2702:2 keypress keyCode:54 which:54
VM2705:2 keyup keyCode:54 which:54
VM2702:2 keypress keyCode:55 which:55
VM2705:2 keyup keyCode:55 which:55
VM2702:2 keypress keyCode:56 which:56
VM2705:2 keyup keyCode:56 which:56
VM2702:2 keypress keyCode:57 which:57
VM2705:2 keyup keyCode:57 which:57
```

**Comment by jediwade** [comment]
Well as long as it is working as expected, I will leave it as keyup for now since I am checking for both conditions. Since you say everything is working as expected, I am going to close this out. Thank you for your feedback and if you come across any other features that would be within the scope of the intent of this extension, I will consider looking into it/them.
